# Generated by Django 3.0.3 on 2020-09-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vendor', '0001_initial'),
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(to='vendor.FoodItemsModel'),
        ),
        migrations.AddField(
            model_name='customerregistrationmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.CityModel'),
        ),
    ]
